# -*- coding: utf-8 -*-
"""Face Mesh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17B-gioWxr-9F7P2LpW-JrC6UJrIp4vRC
"""

import sys
!{sys.executable} -m pip install uniface[cpu]
import cv2
import urllib.request # Import for downloading image

from uniface import SCRFD, FaceMesh

# Initialize detector and Face Mesh
detector = SCRFD()
mesher = FaceMesh()

# Define URL for a sample image and local filename
# Using a publicly accessible image URL that is directly downloadable and valid
image_url = 'https://upload.wikimedia.org/wikipedia/commons/8/8d/President_Barack_Obama.jpg'
image_filename = 'sample_image.png'

# Download the image with User-Agent header to bypass potential 403 Forbidden
try:
    opener = urllib.request.build_opener()
    opener.addheaders = [('User-agent', 'Mozilla/5.0')]
    urllib.request.install_opener(opener)
    urllib.request.urlretrieve(image_url, image_filename)
    print(f"Downloaded {image_filename} from {image_url}")
except Exception as e:
    raise RuntimeError(f"Could not download sample image: {e}")

# Load the downloaded image
image = cv2.imread(image_filename)

# Check if image was loaded successfully
if image is None:
    raise ValueError("Could not load the downloaded image. Please check the image file path and content.")

# Detect faces
faces = detector.detect(image)

# Extract Face Mesh landmarks
results = mesher.predict(image, faces)

# Get the first face
if results:
    result = results[0]

    print("Landmarks:", result.landmarks.shape)  # (468, 3)
    print("2D Points:", result.points_2d.shape)  # (468, 2)
    print("Face Score:", result.score)
else:
    print("No faces detected in the image.")

import matplotlib.pyplot as plt

def draw_landmarks(image, landmarks_2d):
    """Draws 2D landmarks on an image."""
    # Convert image from BGR to RGB for matplotlib display
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(10, 10))
    plt.imshow(image_rgb)
    plt.scatter(landmarks_2d[:, 0], landmarks_2d[:, 1], s=5, c='red', alpha=0.7)
    plt.title('Detected Face Mesh Landmarks')
    plt.axis('off')
    plt.show()

# Check if faces were detected and results are available
if 'result' in locals() and result:
    draw_landmarks(image, result.points_2d)
else:
    print("No face detected or landmarks not available for visualization.")

"""The visualization above shows the image with the detected face mesh landmarks overlaid as red dots. Each dot represents a 2D point on the face.

# **👁️ 478-Point Model with Iris Detection**

# The V2_478 model adds 10 iris landmarks to the standard 468-point mesh
"""

from uniface import SCRFD, FaceMesh
from uniface.constants import FaceMeshWeights

detector = SCRFD()
mesher = FaceMesh(
    model_name=FaceMeshWeights.V2_478
)

faces = detector.detect(image)
results = mesher.predict(image, faces)

if results:
    result = results[0]

    print(result.landmarks.shape)  # (478, 3)

"""# 🔍 Access the Iris Points"""

# جميع نقاط الـ Face Mesh
print("Shape:", result.landmarks.shape)

# أول 468 نقطة
mesh_points = result.landmarks[:468]

# آخر 10 نقاط الخاصة بالقزحية
iris_points = result.landmarks[468:]

print("Mesh:", mesh_points.shape)
print("Iris:", iris_points.shape)

# أول 5 نقاط = قزحية
left_iris = iris_points[:5]

# آخر 5 نقاط = القزحية الأخرى
right_iris = iris_points[5:]

print("Left iris:", left_iris.shape)
print("Right iris:", right_iris.shape)

print(result.landmarks.shape)
print(result.landmarks[468:])

"""# 📐 3D Output

# The landmarks are returned as:
"""

result.landmarks

"""x → horizontal position
y → vertical position
z → relative depth

# If you only need 2D coordinates:

"""

points_2d = result.points_2d

"""# 🎨 Visualization"""

from uniface.draw import draw_mesh

# Partial mesh — recommended for real-time applications
draw_mesh(
    image,
    result.landmarks,
    mode="partial"
)

# Full mesh
draw_mesh(
    image,
    result.landmarks,
    mode="full"
)

# Points only
draw_mesh(
    image,
    result.landmarks,
    mode="points"
)

"""# 🎯 Using Face Bounding Boxes Directly

You can use Face Mesh without running a detector first:
"""

from uniface import SCRFD, FaceMesh
from uniface.constants import FaceMeshWeights

# إنشاء النماذج
detector = SCRFD()
mesher = FaceMesh(
    model_name=FaceMeshWeights.V2_478
)

# اكتشاف الوجوه
faces = detector.detect(image)

print("Number of faces:", len(faces))

# إنشاء Face Mesh
results = mesher.predict(image, faces)

print("Number of results:", len(results))

if results:
    result = results[0]

    print("Landmarks:", result.landmarks.shape)

x1 = 100
y1 = 80
x2 = 400
y2 = 450

results = mesher.predict(
    image,
    bboxes=[[x1, y1, x2, y2]]
)

import os

for file in os.listdir():
    print(file)

import cv2

from uniface import SCRFD, FaceMesh
from uniface.constants import FaceMeshWeights

# =========================
# 1. Load image
# =========================

image_path = "sample_image.png"

image = cv2.imread(image_path)

if image is None:
    raise FileNotFoundError(
        f"Could not load image: {image_path}"
    )

print("✅ Image loaded:", image.shape)


# =========================
# 2. Face Detection
# =========================

detector = SCRFD()

faces = detector.detect(image)

print("👤 Faces detected:", len(faces))


# =========================
# 3. Face Mesh
# =========================

mesher = FaceMesh(
    model_name=FaceMeshWeights.V2_478
)

results = mesher.predict(
    image,
    faces
)


# =========================
# 4. Results
# =========================

if results:
    result = results[0]

    print("✅ Face Mesh:", result.landmarks.shape)
else:
    print("❌ No Face Mesh result")

from uniface.draw import draw_mesh
import cv2

# رسم الـ Face Mesh
output = image.copy()

draw_mesh(
    output,
    result.landmarks,
    mode="partial"
)

# حفظ الصورة
cv2.imwrite(
    "face_mesh_result.jpg",
    output
)

print("✅ Saved: face_mesh_result.jpg")

"""# 👁️ ولعرضها داخل Colab"""

from IPython.display import display
from PIL import Image

display(Image.open("face_mesh_result.jpg"))

"""# إذا أردت الشبكة الكاملة 478 نقطة:"""

draw_mesh(
    output,
    result.landmarks,
    mode="full"
)

draw_mesh(
    output,
    result.landmarks,
    mode="points"
)