# -*- coding: utf-8 -*-
"""01_face_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GL2J71dJ_Qy5tcNih5DPMsw0P3-OuUza
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q "uniface[cpu]"

from google.colab import files

uploaded = files.upload()

import cv2

image = cv2.imread("pngtree-mutiracial-family-sitting-on-beach-together-seven-mutiracial-photo-image_1380633.jpg")

if image is None:
    raise ValueError("Could not load the image.")

from uniface import FaceAnalyzer, FairFace

analyzer = FaceAnalyzer(
    predictors=[FairFace()]
)

for face in analyzer.analyze(image):
    print("Bounding Box:", face.bbox)
    print("Confidence:", face.confidence)
    print("Sex:", face.sex)
    print("Age Group:", face.age_group)
    print("Embedding Shape:", face.embedding.shape)

import cv2
from google.colab import files
from uniface import FaceAnalyzer, FairFace

# Upload an image
uploaded = files.upload()

image_path = next(iter(uploaded))
image = cv2.imread(image_path)

if image is None:
    raise ValueError(f"Could not load image: {image_path}")

# Initialize UniFace
analyzer = FaceAnalyzer(
    predictors=[FairFace()]
)

# Analyze faces
for face in analyzer.analyze(image):
    print("Bounding Box:", face.bbox)
    print("Confidence:", face.confidence)
    print("Sex:", face.sex)
    print("Age Group:", face.age_group)
    print("Embedding Shape:", face.embedding.shape)

import cv2
import IPython.display as display
from PIL import Image

import uniface
from uniface.detection import RetinaFace
from uniface.draw import draw_detections

print(uniface.__version__)

detector = RetinaFace(
    confidence_threshold=0.5,
    nms_threshold=0.4,
)

"""1. Load and Display Input Image"""

image_path = 'pngtree-mutiracial-family-sitting-on-beach-together-seven-mutiracial-photo-image_1380633 (1).jpg'
pil_image = Image.open(image_path)
pil_image

"""# 2. Detect **Faces**"""

# Load image
image = cv2.imread(image_path)

# Detect faces - returns list of Face objects
faces = detector.detect(image)
print(f'Detected {len(faces)} face(s)')

# Draw detections
draw_detections(image=image, faces=faces, vis_threshold=0.6, corner_bbox=True)

# Display result
output_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
display.display(Image.fromarray(output_image))

"""3. Detect Top-K Faces
Use max_num to limit the number of detected faces.

## Top-2 **faces**
"""

image = cv2.imread(image_path)

faces = detector.detect(image, max_num=2)
print(f'Detected {len(faces)} face(s)')

draw_detections(image=image, faces=faces, vis_threshold=0.6, corner_bbox=True)

output_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
display.display(Image.fromarray(output_image))

"""# Top-5 faces"""

image = cv2.imread(image_path)

faces = detector.detect(image, max_num=5)
print(f'Detected {len(faces)} face(s)')

draw_detections(image=image, faces=faces, vis_threshold=0.6, corner_bbox=True)

output_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
display.display(Image.fromarray(output_image))

"""Notes
landmarks are the 5-point alignment template (eyes, nose, mouth corners) that recognition and quality both consume. BlazeFace is the exception: it returns 6 MediaPipe keypoints whose fourth point is a mouth centre, so it cannot be used for alignment.
detect(image, max_num=5) keeps only the strongest faces.
## **New Section** **bold text**
"""